// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYFNqgcnXS1GAk64X2jNEMp8tJJbyxaY',
    appId: '1:272000325126:web:3d90de4c0c45c64cb21587',
    messagingSenderId: '272000325126',
    projectId: 'sapient-4d481',
    authDomain: 'sapient-4d481.firebaseapp.com',
    storageBucket: 'sapient-4d481.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi-FsGj4bfJOjXtaxpX_ySEFGA6fo_5RY',
    appId: '1:272000325126:android:cd862a349270995bb21587',
    messagingSenderId: '272000325126',
    projectId: 'sapient-4d481',
    storageBucket: 'sapient-4d481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEWyA5iQzuKLx3bHLQAohQY8XguHBTaGU',
    appId: '1:272000325126:ios:916c838c904a5375b21587',
    messagingSenderId: '272000325126',
    projectId: 'sapient-4d481',
    storageBucket: 'sapient-4d481.firebasestorage.app',
    iosBundleId: 'com.example.sapient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEWyA5iQzuKLx3bHLQAohQY8XguHBTaGU',
    appId: '1:272000325126:ios:916c838c904a5375b21587',
    messagingSenderId: '272000325126',
    projectId: 'sapient-4d481',
    storageBucket: 'sapient-4d481.firebasestorage.app',
    iosBundleId: 'com.example.sapient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTYFNqgcnXS1GAk64X2jNEMp8tJJbyxaY',
    appId: '1:272000325126:web:0785791c4789f551b21587',
    messagingSenderId: '272000325126',
    projectId: 'sapient-4d481',
    authDomain: 'sapient-4d481.firebaseapp.com',
    storageBucket: 'sapient-4d481.firebasestorage.app',
  );
}
